#!/bin/bash
#docker container run --name child-shell --rm -p 3100:3100 -v /media/cryptfs:/home/6SQw18oY8N/encrypted -it child-shell /bin/bash
docker container run --name flash-shell --rm -p 6100:6100 -p 3100:3100 -v /media/usb:/media/storage -it flash-shell /bin/bash
