#!/bin/bash

#Copy the SSH config file to stop the irritating key prompt
#cp config ~/.ssh/

#Run the docker image
docker run -d --name flash-shell -p 6100:6100 -p 3100:3100 -v /media/usb:/media/storage --restart unless-stopped flash-shell
